const TRANSLATIONS={
en:{
nav_dashboard:'Dashboard',nav_profile:'Farmer Profile',nav_crops:'Crop & Land',
nav_crop_bills:'Crop Sales',nav_dairy:'Dairy & Livestock',nav_milk_bills:'Milk Bills',
nav_customers:'Customers',nav_rates:'Rate Management',nav_payments:'Payment Records',
nav_overview:'OVERVIEW',nav_modules:'MODULES',nav_manage:'MANAGE',nav_settings:'SETTINGS',
role_admin:'Admin · Farmer',topbar_dashboard:'Dashboard',topbar_profile:'Farmer Profile & Land',
topbar_crops:'Crop & Land Management',topbar_crop_bills:'Crop Sales & Bills',
topbar_dairy:'Dairy & Livestock',topbar_milk_bills:'Milk Bills & Supply',
topbar_customers:'Customers',topbar_rates:'Rate Management',topbar_farmers:'Manage Farmers',
lbl_active_crops:'Active Crops',lbl_month_sales:'Crop Sales (Month)',
lbl_milk_today:'Milk Today (L)',lbl_customers:'Customers',
lbl_monthly_sales:'Monthly Crop Sales (₹)',lbl_monthly_milk:'Monthly Milk (L)',
lbl_recent_sales:'Recent Sales',lbl_land:'Land Records',
lbl_all_crops:'All Crop Records',lbl_all_sales:'All Sales',
lbl_all_customers:'All Customers',lbl_milk_log:'Milk Production Log',
col_product:'Product',col_customer:'Customer',col_qty:'Qty',col_amount:'Amount',
col_date:'Date',col_payment:'Payment',col_plot:'Plot No.',col_area:'Area (Acres)',
col_location:'Location',col_soil:'Soil Type',col_irr:'Irrigation',col_crop:'Crop',
col_variety:'Variety',col_land:'Land',col_sow:'Sowing',col_harvest:'Harvest',
col_status:'Status',col_price:'Price/Unit',col_market:'Market',
col_morning:'Morning(L)',col_evening:'Evening(L)',col_total:'Total(L)',
col_sold:'Sold(L)',col_consumed:'Consumed(L)',col_rate:'Rate(₹/L)',
col_earnings:'Earnings(₹)',col_cows:'Cows',col_buffalo:'Buffaloes',
col_name:'Full Name',col_mobile:'Mobile',col_address:'Address',
col_category:'Category',col_added:'Added On',col_actions:'Actions',
btn_add_land:'Add Land',btn_add_crop:'Add Crop',btn_add_sale:'Add Sale',
btn_add_entry:'Add Entry',btn_add_cust:'Add Customer',btn_add_farmer:'Add Farmer',
btn_save:'Save',btn_cancel:'Cancel',btn_update:'Update Profile',
btn_update_rates:'Update Rates',btn_print:'Print Report',
btn_reset_rates:'Reset to Default',lbl_animals:'Update Animal Count',
lbl_full_name:'Full Name',lbl_mobile:'Mobile Number',lbl_email:'Email',
lbl_village:'Village',lbl_taluka:'Taluka',lbl_district:'District',
lbl_password:'Password',lbl_address:'Address',lbl_category:'Category',
lbl_crop_name:'Crop Name',lbl_variety:'Variety',lbl_land_plot:'Land Plot',
lbl_sow_date:'Sowing Date',lbl_harvest_date:'Expected Harvest',
lbl_actual_harvest:'Actual Harvest',lbl_seed_qty:'Seed Qty (kg)',
lbl_water_source:'Water Source',lbl_fertilizer:'Fertilizer Used',
lbl_product:'Product Name',lbl_quantity:'Quantity',lbl_unit:'Unit',
lbl_price:'Price per Unit (₹)',lbl_sale_date:'Sale Date',
lbl_market:'Market Name',lbl_market_loc:'Market Location',
lbl_payment:'Payment Status',lbl_notes:'Notes',
lbl_fat:'FAT %',lbl_snf:'SNF %',lbl_rate:'Rate (₹/L)',
lbl_morning:'Morning Litres',lbl_evening:'Evening Litres',
lbl_sold:'Sold (Litres)',lbl_consumed:'Consumed (Litres)',
lbl_cow_count:'Cow Count',lbl_buf_count:'Buffalo Count',
lbl_animal_type:'Animal Type',lbl_month:'Month',
ph_search:'Search...',ph_name:'Enter full name',ph_mobile:'Mobile number',
ph_plot:'e.g. Plot 12A',ph_area:'e.g. 2.5',ph_location:'Village / Survey',
ph_crop:'e.g. Tomato, Onion',ph_variety:'e.g. Hybrid F1',
ph_product:'e.g. Tomato, Milk',ph_notes:'Additional notes',
ph_fat:'e.g. 4.2',ph_snf:'e.g. 8.5',ph_market:'e.g. Shirol APMC',
ph_market_loc:'City / Area',ph_password:'Set or change password',ph_rate:'e.g. 45',
status_growing:'Growing',status_harvested:'Harvested',status_failed:'Failed',
pay_paid:'Paid',pay_pending:'Pending',pay_partial:'Partial',
cat_milk:'Milk Customer',cat_crop:'Crop Customer',cat_both:'Both',
del_confirm:'Delete this record?',
toast_saved:'Saved!',toast_deleted:'Deleted!',toast_updated:'Updated!',
toast_paid:'Marked as Paid!',toast_settled:'bills settled!',
empty_crops:'No crop records yet',empty_sales:'No sales yet',
empty_customers:'No customers yet',empty_milk:'No milk entries yet',
empty_land:'No land records yet',empty_recent:'No recent sales',
lbl_cow_rates:'Cow Milk Rate Table (FAT × SNF)',
lbl_buf_rates:'Buffalo Milk Rate Table (FAT × SNF)',
lbl_rate_note:'Rates are used automatically when FAT & SNF values are entered.',
lbl_cow_milk:'Cow Milk',lbl_buf_milk:'Buffalo Milk',
lbl_monthly_settle:'Monthly Settlement',lbl_settle_preview:'Pending Bills',
btn_preview:'Preview',btn_confirm_settle:'✅ Mark All Paid',
lbl_pending:'Pending (₹)',lbl_total_billed:'Total Billed (₹)',lbl_paid:'Paid (₹)',
lbl_auto_note:'Milk bills are auto-created when you add a dairy entry with sold litres + rate + customer.',
lbl_add_manual:'Add Manual Bill',lbl_all_customers_opt:'All Customers',
sub_dashboard:'Welcome — your farm at a glance',
sub_profile:'Manage personal details and land records',
sub_crops:'Track sowing, harvest and crop status',
sub_crop_bills:'All crop produce sold in market',
sub_dairy:'Cow & buffalo milk with FAT/SNF rate calculator',
sub_milk_bills:'Milk supply bills — auto-generated from dairy entries',
sub_customers:'Manage milk and crop customers',
sub_rates:'View and update FAT & SNF rate tables',
sub_farmers:'Manage farmer accounts (Super Admin only)',
nav_payments:'Payment Records',lbl_new_mobile:'New Mobile Number',lbl_payment_mode:'Payment Mode',lbl_cash:'Cash',lbl_online:'Online Transfer',lbl_cheque:'Cheque',lbl_upi:'UPI',lbl_reference:'Reference No.',lbl_pay_date:'Payment Date',lbl_pay_amount:'Amount Paid',btn_add_payment:'Add Payment',lbl_supply_type:'Supply Type',lbl_retail:'Retail Customer',lbl_company:'Milk Company',lbl_retail_rate:'Retail Rate (₹/L)',lbl_company_name:'Company Name',lbl_balance:'Balance (₹)',lbl_total_paid:'Total Paid (₹)',lbl_new_password:'New Password',
lbl_confirm_password:'Confirm Password',btn_update_mobile:'Update Mobile',
btn_update_password:'Update Password',lbl_current_password:'Current Password',
},
mr:{
nav_dashboard:'डॅशबोर्ड',nav_profile:'शेतकरी प्रोफाईल',nav_crops:'पीक व जमीन',
nav_crop_bills:'पीक विक्री',nav_dairy:'दुग्धशाळा',nav_milk_bills:'दूध बिल',
nav_customers:'ग्राहक',nav_rates:'दर व्यवस्थापन',nav_payments:'पेमेंट नोंदी',
nav_overview:'सारांश',nav_modules:'मॉड्यूल',nav_manage:'व्यवस्थापन',nav_settings:'सेटिंग',
role_admin:'प्रशासक · शेतकरी',topbar_dashboard:'डॅशबोर्ड',topbar_profile:'शेतकरी प्रोफाईल व जमीन',
topbar_crops:'पीक व जमीन व्यवस्थापन',topbar_crop_bills:'पीक विक्री व बिल',
topbar_dairy:'दुग्धशाळा व पशुधन',topbar_milk_bills:'दूध बिल व पुरवठा',
topbar_customers:'ग्राहक',topbar_rates:'FAT व SNF दर व्यवस्थापन',
topbar_farmers:'शेतकरी व्यवस्थापन',
lbl_active_crops:'सक्रिय पिके',lbl_month_sales:'पीक विक्री (महिना)',
lbl_milk_today:'आजचे दूध (लि)',lbl_customers:'ग्राहक',
lbl_monthly_sales:'मासिक पीक विक्री (₹)',lbl_monthly_milk:'मासिक दूध (लि)',
lbl_recent_sales:'अलीकडील विक्री',lbl_land:'जमीन नोंदी',
lbl_all_crops:'सर्व पीक नोंदी',lbl_all_sales:'सर्व विक्री',
lbl_all_customers:'सर्व ग्राहक',lbl_milk_log:'दूध उत्पादन नोंदी',
col_product:'उत्पादन',col_customer:'ग्राहक',col_qty:'प्रमाण',col_amount:'रक्कम',
col_date:'तारीख',col_payment:'देयक',col_plot:'प्लॉट क्र.',col_area:'क्षेत्र (एकर)',
col_location:'स्थान',col_soil:'मातीचा प्रकार',col_irr:'सिंचन',col_crop:'पीक',
col_variety:'वाण',col_land:'जमीन',col_sow:'पेरणी',col_harvest:'कापणी',
col_status:'स्थिती',col_price:'दर/युनिट',col_market:'बाजार',
col_morning:'सकाळ(लि)',col_evening:'संध्या(लि)',col_total:'एकूण(लि)',
col_sold:'विकले(लि)',col_consumed:'वापर(लि)',col_rate:'दर(₹/लि)',
col_earnings:'उत्पन्न(₹)',col_cows:'गाई',col_buffalo:'म्हशी',
col_name:'पूर्ण नाव',col_mobile:'मोबाईल',col_address:'पत्ता',
col_category:'प्रकार',col_added:'तारीख',col_actions:'क्रिया',
btn_add_land:'जमीन जोडा',btn_add_crop:'पीक जोडा',btn_add_sale:'विक्री जोडा',
btn_add_entry:'नोंद जोडा',btn_add_cust:'ग्राहक जोडा',btn_add_farmer:'शेतकरी जोडा',
btn_save:'जतन करा',btn_cancel:'रद्द करा',btn_update:'प्रोफाईल अपडेट',
btn_update_rates:'दर अपडेट करा',btn_print:'अहवाल छापा',
btn_reset_rates:'डिफॉल्टवर रीसेट',lbl_animals:'प्राणी संख्या अपडेट',
lbl_full_name:'पूर्ण नाव',lbl_mobile:'मोबाईल नंबर',lbl_email:'ईमेल',
lbl_village:'गाव',lbl_taluka:'तालुका',lbl_district:'जिल्हा',
lbl_password:'पासवर्ड',lbl_address:'पत्ता',lbl_category:'प्रकार',
lbl_crop_name:'पिकाचे नाव',lbl_variety:'वाण',lbl_land_plot:'जमीन प्लॉट',
lbl_sow_date:'पेरणी तारीख',lbl_harvest_date:'अपेक्षित कापणी',
lbl_actual_harvest:'प्रत्यक्ष कापणी',lbl_seed_qty:'बियाणे (किग्रॅ)',
lbl_water_source:'पाण्याचा स्रोत',lbl_fertilizer:'खत',
lbl_product:'उत्पादनाचे नाव',lbl_quantity:'प्रमाण',lbl_unit:'युनिट',
lbl_price:'प्रति युनिट किंमत (₹)',lbl_sale_date:'विक्री तारीख',
lbl_market:'बाजाराचे नाव',lbl_market_loc:'बाजाराचे ठिकाण',
lbl_payment:'देयक स्थिती',lbl_notes:'नोंदी',
lbl_fat:'FAT %',lbl_snf:'SNF %',lbl_rate:'दर (₹/लि)',
lbl_morning:'सकाळचे लिटर',lbl_evening:'संध्याकाळचे लिटर',
lbl_sold:'विकलेले (लिटर)',lbl_consumed:'वापरलेले (लिटर)',
lbl_cow_count:'गाईंची संख्या',lbl_buf_count:'म्हशींची संख्या',
lbl_animal_type:'प्राण्याचा प्रकार',lbl_month:'महिना',
ph_search:'शोधा...',ph_name:'पूर्ण नाव टाका',ph_mobile:'मोबाईल नंबर',
ph_plot:'उदा. प्लॉट १२अ',ph_area:'उदा. २.५',ph_location:'गाव / सर्व्हे नंबर',
ph_crop:'उदा. टोमॅटो, कांदा',ph_variety:'उदा. हायब्रिड F१',
ph_product:'उदा. टोमॅटो, दूध',ph_notes:'अतिरिक्त नोंदी',
ph_fat:'उदा. ४.२',ph_snf:'उदा. ८.५',ph_market:'उदा. शिरोळ APMC',
ph_market_loc:'शहर / परिसर',ph_password:'पासवर्ड सेट किंवा बदला',ph_rate:'उदा. ४५',
status_growing:'वाढत आहे',status_harvested:'कापणी झाली',status_failed:'अयशस्वी',
pay_paid:'भरले',pay_pending:'बाकी',pay_partial:'अंशतः',
cat_milk:'दूध ग्राहक',cat_crop:'पीक ग्राहक',cat_both:'दोन्ही',
del_confirm:'हे रेकॉर्ड हटवायचे आहे का?',
toast_saved:'जतन केले!',toast_deleted:'हटवले!',toast_updated:'अपडेट केले!',
toast_paid:'भरले म्हणून नोंदले!',toast_settled:'बिले भरली!',
empty_crops:'अद्याप पीक नोंदी नाहीत',empty_sales:'अद्याप विक्री नाही',
empty_customers:'अद्याप ग्राहक नाहीत',empty_milk:'अद्याप दूध नोंदी नाहीत',
empty_land:'अद्याप जमीन नोंदी नाहीत',empty_recent:'अद्याप विक्री नाही',
lbl_cow_rates:'गाय दूध दर सारणी (FAT × SNF)',
lbl_buf_rates:'म्हैस दूध दर सारणी (FAT × SNF)',
lbl_rate_note:'FAT व SNF मूल्यांमधून दुधाची किंमत आपोआप मोजली जाते.',
lbl_cow_milk:'गाय दूध',lbl_buf_milk:'म्हैस दूध',
lbl_monthly_settle:'मासिक पेमेंट',lbl_settle_preview:'बाकी बिले',
btn_preview:'आढावा घ्या',btn_confirm_settle:'✅ सर्व भरले म्हणून नोंदा',
lbl_pending:'बाकी (₹)',lbl_total_billed:'एकूण बिल (₹)',lbl_paid:'भरले (₹)',
lbl_auto_note:'डेअरी नोंदीत विकलेले लिटर + दर + ग्राहक टाकल्यावर दूध बिल आपोआप तयार होते.',
lbl_add_manual:'हस्तचलित बिल जोडा',lbl_all_customers_opt:'सर्व ग्राहक',
sub_dashboard:'स्वागत — तुमच्या शेताचा आढावा',
sub_profile:'तुमची माहिती आणि जमीन नोंदी',
sub_crops:'पेरणी, कापणी आणि पीक स्थिती',
sub_crop_bills:'बाजारात विकलेल्या पिकांची नोंद',
sub_dairy:'गाय आणि म्हैस दूध — FAT/SNF दर कॅल्क्युलेटर',
sub_milk_bills:'दूध पुरवठा बिले — डेअरी नोंदीतून आपोआप',
sub_customers:'दूध आणि पीक ग्राहक व्यवस्थापन',
sub_rates:'FAT व SNF दर सारणी पहा आणि अपडेट करा',
sub_farmers:'शेतकरी खाती व्यवस्थापन (फक्त मुख्य संचालक)',
nav_payments:'पेमेंट नोंदी',lbl_new_mobile:'नवीन मोबाईल नंबर',lbl_payment_mode:'पेमेंट पद्धत',lbl_cash:'रोख',lbl_online:'ऑनलाईन',lbl_cheque:'चेक',lbl_upi:'UPI',lbl_reference:'संदर्भ क्र.',lbl_pay_date:'पेमेंट तारीख',lbl_pay_amount:'भरलेली रक्कम',btn_add_payment:'पेमेंट जोडा',lbl_supply_type:'पुरवठ्याचा प्रकार',lbl_retail:'रिटेल ग्राहक',lbl_company:'दूध कंपनी',lbl_retail_rate:'रिटेल दर (₹/लि)',lbl_company_name:'कंपनीचे नाव',lbl_balance:'शिल्लक (₹)',lbl_total_paid:'एकूण भरले (₹)',lbl_new_password:'नवीन पासवर्ड',
lbl_confirm_password:'पासवर्ड पुष्टी करा',btn_update_mobile:'मोबाईल अपडेट करा',
btn_update_password:'पासवर्ड अपडेट करा',lbl_current_password:'सध्याचा पासवर्ड',
}};

function getLang(){return localStorage.getItem('sm_lang')||'en';}
function setLang(l){localStorage.setItem('sm_lang',l);applyLang();}
function t(k){return TRANSLATIONS[getLang()][k]||TRANSLATIONS.en[k]||k;}

function applyLang(){
  const l=getLang();
  document.querySelectorAll('[data-t]').forEach(el=>{
    const v=t(el.dataset.t);
    if(el.tagName==='INPUT'||el.tagName==='TEXTAREA') el.placeholder=v;
    else el.textContent=v;
  });
  document.querySelectorAll('.lbtn').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));
  if(typeof onLangChange==='function') onLangChange();
}

document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('.lbtn').forEach(b=>{
    b.classList.toggle('active',b.dataset.lang===getLang());
    b.addEventListener('click',()=>setLang(b.dataset.lang));
  });
  applyLang();
});
