-- Shetkari Mitra — Clean Database (trimmed records)
-- Generated by cleanup script

CREATE DATABASE IF NOT EXISTS shetkari_mitra CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shetkari_mitra;

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `username` varchar(50) DEFAULT NULL,
  `mobile` varchar(15) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `village` varchar(100) DEFAULT NULL,
  `taluka` varchar(100) DEFAULT NULL,
  `district` varchar(100) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bills` (
  `id` int(11) NOT NULL,
  `bill_type` enum('crop','milk') NOT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `product_name` varchar(100) NOT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `unit` varchar(20) DEFAULT 'kg',
  `price_per_unit` decimal(10,2) NOT NULL,
  `total_amount` decimal(10,2) GENERATED ALWAYS AS (`quantity` * `price_per_unit`) STORED,
  `market_name` varchar(100) DEFAULT NULL,
  `market_location` varchar(200) DEFAULT NULL,
  `sale_date` date NOT NULL,
  `payment_status` enum('paid','pending','partial') DEFAULT 'pending',
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `crops` (
  `id` int(11) NOT NULL,
  `land_id` int(11) DEFAULT NULL,
  `crop_name` varchar(100) NOT NULL,
  `variety` varchar(100) DEFAULT NULL,
  `sowing_date` date NOT NULL,
  `expected_harvest` date DEFAULT NULL,
  `actual_harvest` date DEFAULT NULL,
  `area_acres` decimal(10,2) DEFAULT NULL,
  `seed_qty_kg` decimal(10,2) DEFAULT NULL,
  `fertilizer_used` varchar(200) DEFAULT NULL,
  `water_source` varchar(100) DEFAULT NULL,
  `status` enum('growing','harvested','failed') DEFAULT 'growing',
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customers` (
  `id` int(11) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `address` text DEFAULT NULL,
  `category` enum('milk','crop','both') DEFAULT 'both',
  `password_hash` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `customer_type` enum('retail','company') DEFAULT 'retail',
  `retail_milk_rate` decimal(10,2) DEFAULT 0.00,
  `company_name` varchar(100) DEFAULT NULL,
  `retail_cow_rate` decimal(10,2) DEFAULT 0.00,
  `retail_buffalo_rate` decimal(10,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `farmer_rates` (
  `id` int(11) NOT NULL,
  `animal_type` enum('cow','buffalo') NOT NULL,
  `fat_value` decimal(4,1) NOT NULL,
  `snf_value` decimal(4,1) NOT NULL,
  `rate` decimal(10,2) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `land_records` (
  `id` int(11) NOT NULL,
  `plot_number` varchar(50) NOT NULL,
  `area_acres` decimal(10,2) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `soil_type` varchar(100) DEFAULT NULL,
  `irrigation_type` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livestock` (
  `id` int(11) NOT NULL,
  `animal_type` enum('cow','buffalo','both') DEFAULT 'both',
  `cow_count` int(11) DEFAULT 0,
  `buffalo_count` int(11) DEFAULT 0,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `milk_companies` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `milk_production` (
  `id` int(11) NOT NULL,
  `animal_type` enum('cow','buffalo') NOT NULL DEFAULT 'cow',
  `entry_date` date NOT NULL,
  `morning_litres` decimal(10,2) DEFAULT 0.00,
  `evening_litres` decimal(10,2) DEFAULT 0.00,
  `total_litres` decimal(10,2) GENERATED ALWAYS AS (`morning_litres` + `evening_litres`) STORED,
  `fat_percent` decimal(5,2) DEFAULT 0.00,
  `snf_percent` decimal(5,2) DEFAULT 0.00,
  `milk_rate` decimal(10,2) DEFAULT 0.00,
  `sold_litres` decimal(10,2) DEFAULT 0.00,
  `consumed_litres` decimal(10,2) DEFAULT 0.00,
  `earnings` decimal(10,2) GENERATED ALWAYS AS (`sold_litres` * `milk_rate`) STORED,
  `customer_id` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `supply_type` enum('retail','company') DEFAULT 'retail',
  `company_id` int(11) DEFAULT NULL,
  `company_rate` decimal(10,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payments` (
  `id` int(11) NOT NULL,
  `bill_id` int(11) NOT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `amount` decimal(10,2) NOT NULL,
  `payment_mode` enum('cash','online','cheque','upi') NOT NULL DEFAULT 'cash',
  `payment_date` date NOT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `mobile` (`mobile`),
  ADD UNIQUE KEY `username` (`username`);

ALTER TABLE `bills`
  ADD PRIMARY KEY (`id`),
  ADD KEY `customer_id` (`customer_id`);

ALTER TABLE `crops`
  ADD PRIMARY KEY (`id`),
  ADD KEY `land_id` (`land_id`);

ALTER TABLE `customers`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `mobile` (`mobile`);

ALTER TABLE `farmer_rates`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uq_rate` (`animal_type`,`fat_value`,`snf_value`);

ALTER TABLE `land_records`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `livestock`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `milk_companies`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `milk_production`
  ADD PRIMARY KEY (`id`),
  ADD KEY `customer_id` (`customer_id`);

ALTER TABLE `payments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `bill_id` (`bill_id`),
  ADD KEY `customer_id` (`customer_id`);

ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `bills`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `crops`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `customers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `farmer_rates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `land_records`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `livestock`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `milk_companies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `milk_production`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `payments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `bills`
  ADD CONSTRAINT `bills_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL;

ALTER TABLE `crops`
  ADD CONSTRAINT `crops_ibfk_1` FOREIGN KEY (`land_id`) REFERENCES `land_records` (`id`) ON DELETE SET NULL;

ALTER TABLE `milk_production`
  ADD CONSTRAINT `milk_production_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL;

ALTER TABLE `payments`
  ADD CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `payments_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL;

SET FOREIGN_KEY_CHECKS=0;
-- Truncate all tables
TRUNCATE TABLE `admin`;
TRUNCATE TABLE `customers`;
TRUNCATE TABLE `land_records`;
TRUNCATE TABLE `crops`;
TRUNCATE TABLE `livestock`;
TRUNCATE TABLE `milk_companies`;
TRUNCATE TABLE `milk_production`;
TRUNCATE TABLE `bills`;
TRUNCATE TABLE `payments`;

INSERT INTO `admin` (`full_name`, `username`, `mobile`, `email`, `village`, `taluka`, `district`, `password_hash`) VALUES
('Adii Chavan', 'admin', '8625805691', 'as@farm.com', 'Shirol', 'Shirol', 'Kolhapur', '$2y$10$He9FRlYv0TZ1H9htHEVuQuz5E15fRbQncjjp5ciFXAtttGWmuMCaS');

INSERT INTO `customers` (`id`, `full_name`, `mobile`, `address`, `category`, `password_hash`, `created_at`, `customer_type`, `retail_milk_rate`, `company_name`, `retail_cow_rate`, `retail_buffalo_rate`) VALUES
(1, 'Santosh Patil', '9823401001', 'Shirol Naka, Shirol, Kolhapur', 'both', '$2y$10$QxyjeoI7vb3hae79kRoE8OjQ5nC2EMZiqm/478NOw6zxpTIYG6t3W', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(2, 'Ganesh Mane', '9823401002', 'Main Road, Kurundwad, Kolhapur', 'milk', '$2y$10$YJFCukULem9sWoSrGS0URO/xidENGVrbEOu7LdkwqqrC3PZsCa/Tu', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(3, 'Pravin Jadhav', '9823401003', 'Nandre Phata, Sangli', 'crop', '$2y$10$EneacH01T45es439fis7FeprGr/oWQSCl1EXS1VIrtiiA3wy3O/v2', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(4, 'Anil Kore', '9823401004', 'Hupari Road, Shirol, Kolhapur', 'milk', '$2y$10$dqsGIH7SmBS5VxYkKBv/yeMxnUQua712/7bTEWPrORbgXauNWYcQW', '2026-04-12 16:36:12', 'retail', 70.00, '', 40.00, 75.00),
(5, 'Deepak Chougule', '9823401005', 'Borgaon, Shirol, Kolhapur', 'both', '$2y$10$PwfRrZb3LWD9nogFwRlogO1kVMkL08hHVE0jKP6TfU.MErLQtNQ8S', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(6, 'Ravi Patil', '9823401006', 'Yelavi, Shirala, Sangli', 'crop', '$2y$10$CRLvbDS9i3ZJr79iy91NwecB0QDJEG6.rtKWEsIpu2LwW/3RR/heC', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(7, 'Nilesh Kadam', '9823401007', 'Islampur Road, Walwa, Sangli', 'milk', '$2y$10$tsvrs9lH25OxMEP.cTUc3exIM6UdIuVxRChCFYGLd9mD7xuFbO7W2', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(8, 'Sanjay Shinde', '9823401008', 'Takari, Miraj, Sangli', 'both', '$2y$10$t.vu7GMxrX5j/Pit/S2MU.kii.45TV7sbOwTV40mBl8yE/crFm.iu', '2026-04-12 16:36:12', 'retail', 0.00, NULL, 40.00, 75.00),
(9, 'Gokul Dudh Dairy', '91588 94010', 'Rajmudra Nagar, Shirol', 'milk', '$2y$10$HIb1U8J.OAHJ0j7Ra2jtIeD/JQV7Y/zf8E49WwJBXlplFCj.8eGQa', '2026-04-12 17:05:17', 'company', 0.00, 'GOKUL', 0.00, 0.00),
(19, 'Karan Dange', '7040000100', 'Tung', 'milk', '$2y$10$SMf7E/IRbzVVU5ON4dHvxuupQRmUPfwor7qG28VfCSXNrqXyC0ycm', '2026-04-13 07:00:22', 'retail', 65.00, '', 40.00, 75.00);

INSERT INTO `land_records` (`id`, `plot_number`, `area_acres`, `location`, `soil_type`, `irrigation_type`, `created_at`) VALUES
(1, 'Plot No. 12/A', 3.50, 'Shirol, Kolhapur', 'Black Cotton', 'Canal', '2026-04-12 16:36:12'),
(2, 'Plot No. 34/B', 2.00, 'Borgaon, Shirol', 'Black Cotton', 'Drip', '2026-04-12 16:36:12'),
(3, 'Plot No. 67', 1.50, 'Kurundwad, Shirol', 'Alluvial', 'Canal', '2026-04-12 16:36:12'),
(6, 'Gat No. 12/A', 3.50, 'Shirol, Kolhapur', 'Black Cotton', 'Canal', '2026-04-13 01:09:48'),
(7, 'Gat No. 34/B', 2.00, 'Borgaon, Shirol', 'Black Cotton', 'Drip', '2026-04-13 01:09:48');

INSERT INTO `crops` (`id`, `land_id`, `crop_name`, `variety`, `sowing_date`, `expected_harvest`, `actual_harvest`, `area_acres`, `seed_qty_kg`, `fertilizer_used`, `water_source`, `status`, `notes`, `created_at`) VALUES
(1, 1, 'Tomato', 'Hybrid F1 Namdhari', '2026-02-26', '2026-05-07', NULL, 1.50, 0.15, 'DAP, Urea, 19-19-19', 'Canal', 'growing', 'Good plant growth', '2026-04-12 16:36:12'),
(2, 1, 'Coriander', 'Local Deshi', '2026-03-13', '2026-04-27', NULL, 0.75, 8.00, 'Urea, Compost', 'Canal', 'growing', 'First cutting soon', '2026-04-12 16:36:12'),
(3, 2, 'Spinach', 'All Green', '2026-03-18', '2026-05-02', NULL, 0.50, 5.00, 'Compost, Micronutrients', 'Drip', 'growing', 'Healthy growth', '2026-04-12 16:36:12'),
(4, 2, 'Fenugreek', 'Kasuri Methi', '2026-03-23', '2026-05-07', NULL, 0.50, 6.00, 'Compost', 'Drip', 'growing', 'Aromatic variety', '2026-04-12 16:36:12'),
(5, 3, 'Bhindi', 'Arka Anamika', '2026-02-21', '2026-04-22', NULL, 1.00, 3.50, 'DAP, Potash, Urea', 'Canal', 'growing', 'Picking started', '2026-04-12 16:36:12');

INSERT INTO `livestock` (`id`, `animal_type`, `cow_count`, `buffalo_count`, `updated_at`) VALUES
(5, 'both', 6, 4, '2026-04-14 05:14:42');

INSERT INTO `milk_companies` (`id`, `name`, `created_at`) VALUES
(1, 'GOKUL', '2026-04-13 06:30:12'),
(2, 'HATSON', '2026-04-13 06:30:12'),
(3, 'CHITALE', '2026-04-13 06:30:12'),
(4, 'MAHANAND', '2026-04-13 06:30:12'),
(5, 'AMUL', '2026-04-13 06:30:12'),
(6, 'OTHER', '2026-04-13 06:30:12');

INSERT INTO `milk_production` (`id`, `animal_type`, `entry_date`, `morning_litres`, `evening_litres`, `fat_percent`, `snf_percent`, `milk_rate`, `sold_litres`, `consumed_litres`, `customer_id`, `notes`, `created_at`, `supply_type`, `company_id`, `company_rate`) VALUES
(1, 'cow', '2026-03-13', 14.50, 12.00, 4.20, 8.60, 33.60, 22.00, 4.50, 2, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(35, 'cow', '2026-03-30', 16.00, 13.00, 4.60, 8.90, 35.04, 25.00, 4.00, 2, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(93, 'cow', '2026-03-29', 15.50, 12.50, 4.40, 8.70, 33.94, 24.00, 4.00, 2, NULL, '2026-04-13 01:09:48', 'retail', NULL, 0.00),
(151, 'cow', '2026-03-28', 14.00, 11.50, 4.10, 8.50, 33.40, 21.00, 4.50, 7, NULL, '2026-04-13 06:30:12', 'retail', NULL, 0.00),
(215, 'cow', '2026-03-28', 15.00, 12.50, 4.30, 8.80, 34.64, 23.50, 4.00, 2, NULL, '2026-04-14 04:33:34', 'retail', NULL, 0.00),
(2, 'buffalo', '2026-03-13', 9.00, 8.50, 7.20, 9.00, 51.20, 15.50, 2.00, 4, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(36, 'buffalo', '2026-03-30', 11.00, 9.50, 7.70, 9.30, 53.70, 18.50, 2.00, 4, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(94, 'buffalo', '2026-03-29', 9.50, 9.00, 7.40, 9.10, 52.40, 16.50, 2.00, 4, NULL, '2026-04-13 01:09:48', 'retail', NULL, 0.00),
(152, 'buffalo', '2026-03-28', 8.50, 8.00, 7.00, 8.90, 50.50, 14.50, 2.00, 7, NULL, '2026-04-13 06:30:12', 'retail', NULL, 0.00),
(216, 'buffalo', '2026-03-28', 10.00, 9.00, 7.50, 9.20, 53.10, 17.00, 2.00, 4, NULL, '2026-04-14 04:33:34', 'retail', NULL, 0.00),
(39, 'cow', '2026-04-01', 14.50, 12.00, 4.20, 8.60, 33.60, 22.00, 4.50, 7, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(101, 'cow', '2026-04-02', 14.50, 12.00, 4.20, 8.60, 33.60, 22.00, 4.50, 7, NULL, '2026-04-13 01:09:48', 'retail', NULL, 0.00),
(163, 'cow', '2026-04-03', 15.50, 12.50, 4.40, 8.80, 34.64, 24.00, 4.00, 2, NULL, '2026-04-13 06:30:12', 'retail', NULL, 0.00),
(187, 'cow', '2026-04-13', 100.00, 100.00, 5.00, 8.00, 32.90, 200.00, 0.00, 19, '', '2026-04-13 07:02:55', 'retail', NULL, 0.00),
(245, 'cow', '2026-04-12', 16.00, 13.00, 4.60, 8.90, 35.04, 25.00, 4.00, 2, NULL, '2026-04-14 04:33:34', 'retail', NULL, 0.00),
(40, 'buffalo', '2026-04-01', 9.00, 8.50, 7.20, 9.00, 51.20, 15.50, 2.00, 7, NULL, '2026-04-12 16:36:12', 'retail', NULL, 0.00),
(100, 'buffalo', '2026-04-01', 9.50, 8.50, 7.30, 9.10, 51.80, 16.00, 2.00, 4, NULL, '2026-04-13 01:09:48', 'retail', NULL, 0.00),
(160, 'buffalo', '2026-04-01', 9.50, 8.50, 7.30, 9.10, 51.80, 16.00, 2.00, 4, NULL, '2026-04-13 06:30:12', 'retail', NULL, 0.00),
(224, 'buffalo', '2026-04-01', 11.00, 9.50, 7.70, 9.30, 53.70, 18.50, 2.00, 4, NULL, '2026-04-14 04:33:34', 'retail', NULL, 0.00),
(248, 'buffalo', '2026-04-13', 9.50, 9.00, 7.40, 9.10, 52.40, 16.50, 2.00, 4, NULL, '2026-04-14 04:33:34', 'retail', NULL, 0.00);

INSERT INTO `bills` (`id`, `bill_type`, `customer_id`, `product_name`, `quantity`, `unit`, `price_per_unit`, `market_name`, `market_location`, `sale_date`, `payment_status`, `notes`, `created_at`) VALUES
(1, 'crop', 1, 'Tomato', 280.00, 'kg', 22.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-03-15', 'paid', NULL, '2026-04-12 16:36:12'),
(6, 'crop', 3, 'Fenugreek', 35.00, 'kg', 48.00, 'Kurundwad APMC', 'Kurundwad, Kolhapur', '2026-03-28', 'pending', NULL, '2026-04-12 16:36:12'),
(78, 'crop', 6, 'Spinach', 80.00, 'kg', 30.00, 'Sangli APMC', 'Sangli', '2026-03-24', 'paid', NULL, '2026-04-13 01:09:48'),
(149, 'crop', 5, 'Bhindi', 120.00, 'kg', 18.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-03-21', 'paid', NULL, '2026-04-13 06:30:12'),
(225, 'crop', 3, 'Coriander', 45.00, 'kg', 55.00, 'Kurundwad APMC', 'Kurundwad, Kolhapur', '2026-03-20', 'paid', NULL, '2026-04-14 04:33:34'),
(296, 'crop', 1, 'Tomato', 280.00, 'kg', 22.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-03-17', 'paid', NULL, '2026-04-14 05:14:42'),
(13, 'milk', 2, 'Cow Milk', 22.00, 'litre', 33.60, NULL, NULL, '2026-03-13', 'paid', NULL, '2026-04-12 16:36:12'),
(42, 'milk', 7, 'Buffalo Milk', 14.50, 'litre', 50.50, NULL, NULL, '2026-03-27', 'paid', NULL, '2026-04-12 16:36:12'),
(107, 'milk', 2, 'Cow Milk', 25.00, 'litre', 36.74, NULL, NULL, '2026-03-24', 'paid', NULL, '2026-04-13 01:09:48'),
(172, 'milk', 4, 'Buffalo Milk', 14.50, 'litre', 50.10, NULL, NULL, '2026-03-20', 'paid', NULL, '2026-04-13 06:30:12'),
(242, 'milk', 2, 'Cow Milk', 24.00, 'litre', 34.64, NULL, NULL, '2026-03-18', 'paid', NULL, '2026-04-14 04:33:34'),
(309, 'milk', 4, 'Buffalo Milk', 15.50, 'litre', 51.20, NULL, NULL, '2026-03-15', 'paid', NULL, '2026-04-14 05:14:42'),
(8, 'crop', 6, 'Maize', 600.00, 'kg', 14.00, 'Sangli APMC', 'Sangli', '2026-04-02', 'partial', NULL, '2026-04-12 16:36:12'),
(81, 'crop', 5, 'Bhindi', 95.00, 'kg', 20.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-04-01', 'paid', NULL, '2026-04-13 01:09:48'),
(86, 'crop', 6, 'Bhindi', 120.00, 'kg', 22.00, 'Sangli APMC', 'Sangli', '2026-04-12', 'pending', '', '2026-04-13 01:09:48'),
(157, 'crop', 5, 'Spinach', 70.00, 'kg', 28.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-04-10', 'pending', NULL, '2026-04-13 06:30:12'),
(232, 'crop', 1, 'Coriander', 55.00, 'kg', 60.00, 'Shirol APMC', 'Shirol, Kolhapur', '2026-04-06', 'paid', NULL, '2026-04-14 04:33:34'),
(303, 'crop', 6, 'Maize', 600.00, 'kg', 14.00, 'Sangli APMC', 'Sangli', '2026-04-04', 'partial', NULL, '2026-04-14 05:14:42'),
(51, 'milk', 7, 'Cow Milk', 22.00, 'litre', 33.60, NULL, NULL, '2026-04-01', 'paid', NULL, '2026-04-12 16:36:12'),
(72, 'milk', 4, 'Buffalo Milk', 16.50, 'litre', 52.40, NULL, NULL, '2026-04-11', 'paid', NULL, '2026-04-12 16:36:12'),
(141, 'milk', 7, 'Cow Milk', 23.50, 'litre', 34.64, NULL, NULL, '2026-04-10', 'paid', NULL, '2026-04-13 01:09:48'),
(210, 'milk', 4, 'Buffalo Milk', 15.50, 'litre', 51.20, NULL, NULL, '2026-04-08', 'paid', NULL, '2026-04-13 06:30:12'),
(278, 'milk', 2, 'Cow Milk', 23.00, 'litre', 33.94, NULL, NULL, '2026-04-05', 'paid', NULL, '2026-04-14 04:33:34'),
(345, 'milk', 4, 'Buffalo Milk', 16.00, 'litre', 51.80, NULL, NULL, '2026-04-02', 'paid', NULL, '2026-04-14 05:14:42');

INSERT INTO `payments` (`id`, `bill_id`, `customer_id`, `amount`, `payment_mode`, `payment_date`, `reference_no`, `notes`, `created_at`) VALUES
(1, 74, 9, 4471.00, 'upi', '2026-04-13', '', '', '2026-04-13 06:34:12'),
(2, 145, 2, 814.00, 'cash', '2026-04-13', '', '', '2026-04-13 06:38:26'),
(3, 145, 2, 814.56, 'upi', '2026-04-13', '', '', '2026-04-13 06:57:20'),
(4, 366, 2, 814.56, 'cash', '2026-04-14', '', 'Recorded from Dairy page', '2026-04-14 05:15:28'),
(5, 295, 4, 864.60, 'upi', '2026-04-14', '', 'Recorded from Dairy page', '2026-04-14 05:15:42'),
(6, 220, 9, 6346.00, 'cheque', '2026-04-14', '', 'Recorded from Dairy page', '2026-04-14 05:15:53'),
(7, 370, 19, 112500.00, 'online', '2026-04-14', '', 'Recorded from Milk Bills page', '2026-04-14 11:49:59');

SET FOREIGN_KEY_CHECKS=1;